lib/phbank_web/router.ex
defmodule PhbankWeb.Router do
  use PhbankWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhbankWeb do
    pipe_through :browser
    get "/test", CurrentAccController, :test
    live("/", Live.CurrentAccs.Index)
    live "/current_accs", Live.CurrentAccs.Index
    live "/current_acc/:id", Live.CurrentAccs.Show
    live "/current_acc/:id/edit", Live.CurrentAccs.Edit

    resources "/current_acc", CurrentAccController
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhbankWeb do
  #   pipe_through :api
  # end
end

lib/phbank_web/templates/page/current_accs.html.leex
<h2>Current accounts</h2>

<table>
  <thead>
    <tr>
      <th>Account Number</th>
      <th>Balance</th>
      <th>Status</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for current_acc <- @current_accs do %>
    <tr>
      <td><%= current_acc.accountNumber %></td>
      <td><%= current_acc.balance %></td>
      <td><%= current_acc.status %></td>
      <td>
        <span><%= link "details", to: Routes.current_acc_path(@socket, :show, current_acc) %>&nbsp; &nbsp;</span>
        <span><%= link "deposit / withdraw", to: Routes.current_acc_path(@socket, :edit, current_acc) %>&nbsp; &nbsp;</span>
        <span><%= link "close", to: Routes.current_acc_path(@socket, :delete, current_acc), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<button phx-click="prevPage">< previous 4</button>
&nbsp;
page <%= @val %>
&nbsp;
<button phx-click="nextPage">next 4 ></button>